//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeoQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingURL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TestingURL()
        {
            this.TestingResult = new HashSet<TestingResult>();
        }
    
        public int Id { get; set; }
        public int TestId { get; set; }
        public Nullable<System.DateTime> AllowedStartDate { get; set; }
        public Nullable<System.DateTime> AllowedEndDate { get; set; }
        public Nullable<int> NumberOfRuns { get; set; }
    
        public virtual Test Test { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TestingResult> TestingResult { get; set; }
    }
}
