//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeoQuiz.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestingResultAnswer
    {
        public int Id { get; set; }
        public int TestingResultId { get; set; }
        public int TestQuestionId { get; set; }
        public string TestAnswersSelected { get; set; }
    
        public virtual TestingResult TestingResult { get; set; }
        public virtual TestQuestion TestQuestion { get; set; }
    }
}
